import { redirect } from "next/navigation";
import { AppNav } from "@/components/app-nav";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { cancelRequestAction, respondToRequestAction } from "./actions";

type RequestRow = { id: string; status: string; message: string | null; requested_at: string; borrower_id: string; lender_id: string; copy_id: string; physical_copies: { title: string; author: string } | null; borrower: { display_name: string } | null; lender: { display_name: string } | null };

export default async function RequestsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user || user.is_anonymous) redirect("/auth");
  const { data } = await supabase.from("loan_requests").select("id, status, message, requested_at, borrower_id, lender_id, copy_id, physical_copies(title, author), borrower:profiles!loan_requests_borrower_id_fkey(display_name), lender:profiles!loan_requests_lender_id_fkey(display_name)").or(`borrower_id.eq.${user.id},lender_id.eq.${user.id}`).order("requested_at", { ascending: false });
  const requests = (data ?? []) as unknown as RequestRow[];
  const { error } = await searchParams;

  return <main className="min-h-screen px-6 py-8 sm:px-10 lg:px-16"><div className="mx-auto max-w-5xl"><AppNav active="dashboard" /><div className="mt-14"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[var(--apricot)]">Lending requests</p><h1 className="mt-4 font-display text-5xl leading-tight">Books in motion.</h1><p className="mt-5 text-lg leading-8 text-[var(--ink-muted)]">Requests you have made and requests waiting for your response.</p>{error && <p role="alert" className="mt-8 rounded-xl bg-[#f7d7c2] px-4 py-3 text-sm">{error}</p>}<div className="mt-10 space-y-4">{requests.length === 0 && <div className="rounded-2xl border border-dashed p-8 text-[var(--ink-muted)]">No lending requests yet.</div>}{requests.map((request) => { const isLender = request.lender_id === user.id; const person = isLender ? request.borrower?.display_name : request.lender?.display_name; return <article key={request.id} className="rounded-2xl border bg-[var(--paper)] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[var(--apricot)]">{isLender ? "Request for your book" : "Your request"}</p><h2 className="mt-2 font-display text-2xl">{request.physical_copies?.title ?? "Book"}</h2><p className="text-sm text-[var(--ink-muted)]">{request.physical_copies?.author} with {person ?? "community member"}</p></div><span className="rounded-full bg-[var(--leaf)] px-3 py-1 text-xs font-bold uppercase">{request.status}</span></div>{request.message && <p className="mt-5 border-l-2 border-[var(--apricot)] pl-4 text-sm leading-6 text-[var(--ink-muted)]">{request.message}</p>}{request.status === "requested" && <div className="mt-5 flex flex-wrap gap-3">{isLender ? <><form action={respondToRequestAction}><input type="hidden" name="requestId" value={request.id} /><input type="hidden" name="decision" value="approved" /><button className="rounded-xl bg-[var(--forest)] px-4 py-2.5 text-sm font-bold text-white">Approve</button></form><form action={respondToRequestAction}><input type="hidden" name="requestId" value={request.id} /><input type="hidden" name="decision" value="declined" /><button className="rounded-xl border px-4 py-2.5 text-sm font-bold">Decline</button></form></> : <form action={cancelRequestAction}><input type="hidden" name="requestId" value={request.id} /><button className="rounded-xl border px-4 py-2.5 text-sm font-bold">Cancel request</button></form>}</div>}</article>; })}</div></div></div></main>;
}